### ISSUE TITLE
-lunwind missing

### ISSUE THREAD

**Issue by ashok3t** [samsk/log-malloc2#2]
On Ubuntu 16.04 with gcc 5.4, _log-malloc -o /tmp/log_ fails with:
  symbol lookup error: /usr/local/lib/liblog-malloc2.so: undefined symbol: _Ux86_64_getcontext

git clone https://github.com/samsk/log-malloc2.git
cd log-malloc
.configure
make
sudo make install

ldd /usr/local/lib/liblog-malloc2.so	linux-vdso.so.1 =>  (0x00007ffcf2ba6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd5d9f4d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd5d9d49000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd5d997f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd5da16a000)

$ nm /usr/lib/x86_64-linux-gnu/libunwind.a | grep _Ux86_64_getcontext
                 U _Ux86_64_getcontext
                 U _Ux86_64_getcontext_trace
                 U _Ux86_64_getcontext
                 U _Ux86_64_getcontext
                 U _Ux86_64_getcontext
                 U _Ux86_64_getcontext
                 U _Ux86_64_getcontext
0000000000000000 T _Ux86_64_getcontext
0000000000000071 T _Ux86_64_getcontext_trace

I patched LDFLAGS as:
       LDFLAGS="$LDFLAGS -lunwind-generic -lunwind"

$ ldd -v /usr/local/lib/liblog-malloc2.so
	linux-vdso.so.1 =>  (0x00007ffe80496000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f4a910bc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4a90e9f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4a90c9b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a908d1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4a912d7000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f4a906af000)

Now I go on to fail with:
 ***MEMORY-ERROR***: [25619]: GSlice: failed to allocate 1008 bytes (alignment: 1024): Cannot allocate memory

**Comment by samsk** [comment]
Funny, on debian/gentoo it works also without it. But added it, thanks for reporting.

Your memory error might be caused calloc(), or memalign not correctly aligning memory, because the library is prepending tracking structure to each allocated memory, and I wanted to avoid allocating more memory than needed for this.
Maybe now, when we all have plenty of memory, it might be worth it to change it and recalculate calloc() parameter and use it for memory allocation...

**Comment by ashok3t** [comment]
Works like a charm on Ubuntu 16.04 and 18.04, thanks for the fast fix!

Also, the MEMORY-ERROR mentioned tangentially does not occur when the target command is vim for instance.
